<?php

use models\cao\CAOGroup;
use models\documenten\Document;

defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Account en userbeheer
 */

class Welkom extends MY_Controller {


	//-----------------------------------------------------------------------------------------------------------------
	// Constructor
	//-----------------------------------------------------------------------------------------------------------------
	public function __construct()
	{
		parent::__construct();
		
		$this->smarty->assign( 'av', $this->werkgever->AVhtml() );
		$this->smarty->assign( 'werkgever', $this->werkgever->bedrijfsgegevens() );
	}
	
	//-----------------------------------------------------------------------------------------------------------------
	// inlener
	//-----------------------------------------------------------------------------------------------------------------
	public function inlener()
	{
		$CAOgroup = new CAOGroup();
		
		
		//geen onterechte redirect
		if( !$this->inlener->blockAccess() )
			redirect( $this->config->item( 'base_url' ) . 'dashboard/inlener'  ,'location' );
		
		//documenten aanmaken voor inlener
		if( $this->inlener->autoGenerateDocuments() )
		{
			foreach( $this->inlener->blockingDocuments() as $array )
			{
				$document = new Document( $array['document_id'] );
				$document_details[] = $document->details();
			}
			
			//show($document_details);
			$this->smarty->assign( 'document_details', $document_details );
		}
		
		$caos = $CAOgroup->inlener( $this->inlener->inlener_id );
		$first_cao = current($caos);
		$cao_id_selected = $first_cao['cao_id_intern'];
		
		$this->smarty->assign( 'caos', $CAOgroup->all() );
		$this->smarty->assign( 'cao_id_selected', $cao_id_selected );
		$this->smarty->assign( 'inlener_id', $this->inlener->inlener_id );
		$this->smarty->assign( 'accepted_av', $this->inlener->acceptedAV() );
		$this->smarty->display('welkom/inlener.tpl');
	}
	

	//-----------------------------------------------------------------------------------------------------------------
	// uitzender
	//-----------------------------------------------------------------------------------------------------------------
	public function uitzender()
	{
		//geen onterechte redirect
		if( !$this->uitzender->blockAccess() )
			redirect( $this->config->item( 'base_url' ) . 'dashboard/uitzender'  ,'location' );
		
		//documenten aanmaken voor uitzender
		if( $this->uitzender->autoGenerateDocuments() )
		{
			foreach( $this->uitzender->blockingDocuments() as $array )
			{
				$document = new Document( $array['document_id'] );
				$document_details[] = $document->details();
			}

			//show($document_details);
			$this->smarty->assign( 'document_details', $document_details );
		}
		
		
		$this->smarty->assign( 'uitzender_id', $this->uitzender->uitzender_id );
		$this->smarty->assign( 'accepted_av', $this->uitzender->acceptedAV() );
		$this->smarty->display('welkom/uitzender.tpl');
	}

}
