<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="template/global_assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
<link href="template/global_assets/css/icons/material/styles.min.css" rel="stylesheet" type="text/css">
<link href="template/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="template/assets/css/bootstrap_limitless.css" rel="stylesheet" type="text/css">
<link href="template/assets/css/layout.css" rel="stylesheet" type="text/css">
<link href="template/assets/css/components.css" rel="stylesheet" type="text/css">
<link href="template/assets/css/colors.min.css" rel="stylesheet" type="text/css">
<link href="recources/css/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="recources/css/custom.css" rel="stylesheet" type="text/css">
<link href="recources/css/verloning_input.css" rel="stylesheet" type="text/css">