<?php

use models\documenten\DocumentFactory;
use models\documenten\Template;
use models\utils\DBhelper;

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

/*
 * Inlener class
 * Wordt met inlener inloggen geladen en is overal beschikbaar
 *
 *
 */

class Inlener_model extends MY_Model
{
	/*
	 * @var int
	 * inlener id
	 */
	public $inlener_id = NULL;
	public $id = NULL;
	public $_redirect_url = NULL;
	
	//templates van documenten die getekend moeten worden
	private $_blocked_template_ids = NULL;
	
	/*
	 * @var array
	 * entiteiteb
	 */
	
	private $_error = NULL;

	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * construct
	 *
	 */
	public function __construct()
	{
		parent::__construct();

		//inlener id
		if( isset( $_SESSION['logindata']['override']['inlener_id'] ) )
			$this->inlener_id = $_SESSION['logindata']['override']['inlener_id'];
		else
			$this->inlener_id = $_SESSION['logindata']['main']['inlener_id'];

		$this->id = $this->inlener_id;
	}



	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * Zijn er nog documenten/acties die de inlener moet uitvoeren
	 *
	 * @return boolean
	 */
	public function blockAccess()
	{
		//AV geaccepteerd?
		if( $this->acceptedAV() === false )
		{
			$this->_redirect_url = 'welkom/inlener';
			return true;
		}
		
		//alles getekend?
		if( $this->allDocumentsSigned() === false )
		{
			$this->_redirect_url = 'welkom/inlener';
			return true;
		}
		
		return false;
	}
	
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * alle documenten getekend?
	 *
	 * @return bool
	 */
	public function allDocumentsSigned()
	{
		$sql = "SELECT documenten.document_id
				FROM documenten
				LEFT JOIN documenten_templates_settings ON documenten_templates_settings.template_id = documenten.template_id
				WHERE inlener_id = $this->inlener_id AND documenten.deleted = 0 AND documenten_templates_settings.deleted = 0
				AND documenten.signed = 0 AND documenten_templates_settings.block_access = 1
				";
		
		$query = $this->db_user->query( $sql );

		if( $query->num_rows() > 0 )
			return false;
		
		return true;
	}
	
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * waar moeten we dan heen als er nog wat te doen is
	 *
	 * @return string
	 */
	public function redirectUrl()
	{
		return $this->_redirect_url;
	}
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * Blocked = 1 ophalend
	 *
	 * @return void
	 */
	public function _getBlockingTemplates()
	{
		$sql = "SELECT template_id, template_name FROM documenten_templates_settings WHERE owner = 'inlener' AND block_access = 1 AND deleted = 0";
		$query = $this->db_user->query( $sql );
		
		$this->_blocked_template_ids = DBhelper::toArray( $query, 'template_id', 'NULL' );
	}
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * Kijken welke document noodzakelijk zijn om verder te mogen (blok access = 1) en deze aanmaken
	 *
	 * @return boolean
	 */
	public function autoGenerateDocuments()
	{
		$this->_getBlockingTemplates();
		
		//geen documten die blokkeren? dan terug
		if( $this->_blocked_template_ids === NULL )
			return false;
		
		//alle documenten nu maken indien nodig
		foreach( $this->_blocked_template_ids as $template_id => &$template )
		{
			if( $this->getDocumentID( $template_id ) === NULL )
				$this->_autoGenerateOvereenkomst( $template_id );
			
			$template['document_id'] = $this->getDocumentID( $template_id );
		}
		
		return true;
	}
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * document info terug
	 *
	 * @return array|void
	 */
	public function blockingDocuments()
	{
		return $this->_blocked_template_ids;
	}
	
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * Overeenkomst maken
	 *
	 *@return void
	 */
	private function _autoGenerateOvereenkomst( $template_id )
	{
		$template = new Template( $template_id ); //4 is samenwerkingsovereenkomst
		$document = DocumentFactory::createFromTemplateObject( $template );
		$document->setInlenerID( $this->inlener_id )->build()->pdf();
	}
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * document ID ophalen
	 *
	 *@return int?
	 */
	public function getDocumentID( $template_id )
	{
		$sql = "SELECT document_id FROM documenten WHERE inlener_id = $this->inlener_id AND deleted = 0 AND template_id = $template_id LIMIT 1";
		$query = $this->db_user->query( $sql );
		
		$row = DBhelper::toRow( $query, 'NULL' );
		if( $row === NULL )
			return $row;
		
		return $row['document_id'];
	}
	
	
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * Algemene voorwaarden accepteren
	 *
	 * @return boolean
	 */
	public function acceptedAV()
	{
		$sql = "SELECT id FROM inleners_av_accepted WHERE inlener_id = $this->inlener_id AND deleted = 0 LIMIT 1";
		$query = $this->db_user->query( $sql );
		
		if( $query->num_rows() == 0 )
			return false;
		return true;
	}
	
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * Algemene voorwaarden accepteren
	 *
	 * @return boolean
	 */
	public function acceptAV()
	{
		$insert['av_id'] = $this->werkgever->AVID();
		$insert['inlener_id'] = $this->inlener_id;
		$insert['accepted_by'] = $this->user->user_id;
		$insert['accepted_ip'] = $_SERVER['REMOTE_ADDR'];
		$insert['accepted_device'] = $_SERVER['HTTP_USER_AGENT'];
		
		$this->db_user->insert( 'inleners_av_accepted', $insert );
		
		if( $this->db_user->insert_id() > 0 )
			return true;
		return false;
	}

	
	
	/**----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	/*
	 * Toon errors
	 * @return array|boolean
	 */
	public function errors()
	{
		//output for debug
		if( isset($_GET['debug']) )
		{
			if( $this->_error === NULL )
				show('Geen errors');
			else
				show($this->_error);
		}

		if( $this->_error === NULL )
			return false;

		return $this->_error;
	}

}


?>